/patrol_node:
  ros__parameters:
    initial_point: [0.0, 0.0, 0.0]
    target_points: [
      0.0, 0.0, 0.0,
      3.75, 4.0, 1.57,
      -6.0, -3.5, 1.57,
      -6.0, 4.0, 0.0,
      6.0, -4.0, 1.57,
    ]
    use_sim_time: false